name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - streamlit
  - jupyter
  - langchain
  - langchain-core
  - langchain-community
  - langchain-huggingface
  - langchain-text-splitters
  - python-dotenv


